import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Italiana, Roboto } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const italiana = Italiana({
  weight: "400",
  subsets: ["latin"],
  variable: "--headerText",
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--smallText",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italiana.variable} ${roboto.variable} antialiased`}
      ><ReduxProvider>{children}</ReduxProvider>
       
      </body>
    </html>
  );
}
